###
# get all orders
GET http://localhost:7070/shop/v1/orders

###
# get one order by id
GET http://localhost:7070/shop/v1/order/1

###
# create a new order 
POST http://localhost:7070/shop/v1/order
Content-Type: application/json

{
    "customer_id": 1,
    "price": 400.00,
    "product":"charger"
}

###
# delete an order by id
DELETE http://localhost:7070/shop/v1/order/3

###
# update an order by id
PATCH  http://localhost:7070/shop/v1/order/1
Content-Type: application/json

{
    "customer_id": 1,
    "price": 500.00,
    "product":"watch"
}